### ISSUE TITLE
com.dnslin:dnslinUtilsn 这个jar能公开下吗

### ISSUE THREAD

**Issue by a1667834841** [dnslin/Onemanager-java#2]
我想试着写下 所以想能不能把这个jar公开下

**Comment by dnslin** [comment]
> 我想试着写下 所以想能不能把这个jar公开下

我另一个仓库有 你clone后自己打个包就行了
那个utils其实不太完美 我感觉很多东西可以丰富，你可以在此基础上加自己的东西
